[
build-system
]
requires = ["hatchling"]
build-backend = "hatchling.build"

[
project
]
name = "trading-strategy-framework"
version = "0.1.0"
authors = [
  { name="Your Name", email="your.email@example.com" }
]
description = "A flexible trading strategy framework"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.0.0",
    "pandas>=2.0.0",
    "numpy>=1.22.0",
    "rich>=10.0.0"
]

[
project.optional-dependencies
]
dev = [
    "pytest>=7.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0"
]

[
tool.ruff
]
line-length = 100
target-version = "py39"

[
tool.mypy
]
strict = true