[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trading_strategy"
version = "0.1.0"
description = "A trading strategy implementation"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
